image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true

build_script:
  - cmd: dotnet --version
  - cmd: cd ./Realmar.Pipes.Tests
  - cmd: dotnet restore
  - cmd: dotnet xunit