image: Visual Studio 2017

version: 0.1.0+{build}-{branch}
skip_branch_with_pr: false
clone_depth: 1

configuration:
  - Debug
  - Release

init:
  - ps: >-
      git config --global core.autocrlf true
      dotnet --version

before_build:
  - ps: >-
      choco install -y opencover.portable
      choco install -y codecov

build_script:
  - ps: >-
      dotnet build -c $CONFIGURATION

      #  tests assemblies
      cd ./Realmar.Pipes.Tests
      dotnet restore

test_script:
  - ps: >-
      OpenCover.Console.exe
        -register:user
        -target:"dotnet.exe"
        -targetargs:"xunit -c $CONFIGURATION"
        -filter:"+[*]* -[*.Tests]*"
        -output:"..\Realmar.Pipes_coverage.xml"
        -oldstyle
        -returntargetcode
        -excludebyattribute:*.ExcludeFromCodeCoverage*

after_test:
  - ps: >-
      cd ..
      codecov -f ".\Realmar.Pipes_coverage.xml"

artifacts:
  - path: .\Realmar.Pipes\bin\$(configuration)\*.nupkg
    name: NuGet.File
  
  - path: .\Realmar.Pipes\bin\$(configuration)\**\*.dll
  - path: .\Realmar.Pipes\bin\$(configuration)\**\*.pdb
  - path: .\Realmar.Pipes\bin\$(configuration)\**\*.xml

deploy:
  provider: NuGet
  api_key:
    secure: Dt0Cdhxr1YD5kwohkW9VMj0LGQj5dLT/hEEV8PRXyE3x5FcRxV01Urn8qsHo8mq5
  skip_symbols: false
  artifact: NuGet.File
  configuration: Release
  on:
    appveyor_repo_tag: true