image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true
  - cmd: dotnet --version

before_build:
  - cmd: choco install -y opencover.portable
  - cmd: choco install -y codecov

build_script:
  - cmd: cd ./Realmar.Pipes.Tests
  - cmd: dotnet restore

test_script:
  - cmd: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"xunit" -filter:"+[*]* -[*.Tests]*" -output:"..\Realmar.Pipes_coverage.xml" -oldstyle -returntargetcode

after_test:
  - cmd: codecov -f "..\Realmar.Pipes_coverage.xml"