image: Visual Studio 2017

version: 1.0.0-alpha+{build}-{branch}

skip_tags: true
skip_branch_with_pr: false

init:
  - cmd: git config --global core.autocrlf true
  - cmd: dotnet --version

before_build:
  - cmd: choco install -y opencover.portable
  - cmd: choco install -y codecov

build_script:
  - cmd: cd ./Realmar.Pipes.Tests
  - cmd: dotnet restore

test_script:
  - cmd: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"xunit" -filter:"+[*]* -[*.Tests]*" -output:"..\Realmar.Pipes_coverage.xml" -oldstyle -returntargetcode -excludebyattribute:*.ExcludeFromCodeCoverage*

after_test:
  - cmd: codecov -f "..\Realmar.Pipes_coverage.xml"